<a href="https://colab.research.google.com/github/natangarcia-gnoss/GNOSS-Modulo-2-Data/blob/main/Recolecci%C3%B3n_desde_BBDD_Modulo_2_GNOSS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tarea 2.2. Recolección desde BBDD##

En esta tarea de usara el dataset de tenis propuesto en la tarea (https://github.com/JeffSackmann/tennis_atp), pese a el archivo esta disponible para su descarga desde la web de Github en este enfoque se tratara el acceso a traves la api de GitHub para posteriormente procesarlo desde Google Colab

In [ ]:
import requests
import pandas as pd
import base64

Podemos bien leerlo con wget para tener el archivo descargado si queremos hacer varias cosas con su contenido:

In [17]:
!wget "https://raw.githubusercontent.com/JeffSackmann/tennis_atp/a36a13fe21f9d0e8ea45a78b3a425ac9bf7a6991/atp_matches_2003.csv"

--2024-09-16 09:58:09--  https://raw.githubusercontent.com/JeffSackmann/tennis_atp/a36a13fe21f9d0e8ea45a78b3a425ac9bf7a6991/atp_matches_2003.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 649296 (634K) [text/plain]
Saving to: ‘atp_matches_2003.csv’

atp_matches_2003.cs 100%[===================>] 634.08K  3.57MB/s    in 0.2s

2024-09-16 09:58:09 (3.57 MB/s) - ‘atp_matches_2003.csv’ saved [649296/649296]

O bien podemos leerlo directemente con pandas si solo queremos almacenar su contenido en un data frame.

In [18]:
# URL del archivo RAW en GitHub (necesario porque al acceder a la URL de github intentara descargar el HTML de la pagina)
url = "https://raw.githubusercontent.com/JeffSackmann/tennis_atp/a36a13fe21f9d0e8ea45a78b3a425ac9bf7a6991/atp_matches_2003.csv"
df = pd.read_csv(url, on_bad_lines='skip')

# Mostrar las primeras filas para verificar que se cargó correctamente
df.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2003-1536,Madrid Masters,Hard,48,M,20031013,1,101965,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,28.0,1090.0,42.0,865.0
1,2003-1536,Madrid Masters,Hard,48,M,20031013,2,102358,NaN,Q,...,NaN,NaN,NaN,NaN,NaN,NaN,146.0,258.0,40.0,950.0
2,2003-1536,Madrid Masters,Hard,48,M,20031013,3,102998,NaN,Q,...,NaN,NaN,NaN,NaN,NaN,NaN,57.0,660.0,43.0,855.0
3,2003-1536,Madrid Masters,Hard,48,M,20031013,4,102610,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,23.0,1170.0,22.0,1190.0
4,2003-1536,Madrid Masters,Hard,48,M,20031013,5,102374,NaN,WC,...,NaN,NaN,NaN,NaN,NaN,NaN,127.0,290.0,49.0,788.0

La libreria de pandas nos ofrece las principales metricas estadisticas sobre dataframes, lo cual nos puede dar de manera sencilla una buena primera aproximación a nustros datos.

In [33]:
df.describe()

,draw_size,tourney_date,match_num,winner_id,winner_seed,winner_ht,winner_age,loser_id,loser_seed,loser_ht,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
count,3218.000000,3.218000e+03,3218.000000,3218.000000,1241.000000,3109.000000,3218.000000,3218.000000,700.000000,3038.000000,...,2809.000000,2809.000000,2809.000000,2809.000000,2809.000000,2809.000000,3174.000000,3174.000000,3128.000000,3128.000000
mean,52.525792,2.003031e+07,26.401802,103195.221255,7.049960,184.443551,25.145649,103229.083592,8.815714,184.332456,...,46.989676,30.961552,14.965824,12.107868,4.716269,8.732645,82.880907,1091.037177,121.991688,727.004795
std,37.585267,1.589890e+03,27.006242,810.524768,6.724468,6.413702,3.443221,985.724967,7.157659,6.573267,...,18.931996,13.938661,7.348002,4.152639,3.336156,4.269176,140.873068,957.652852,175.135490,676.126281
min,4.000000,2.002123e+07,1.000000,101532.000000,1.000000,168.000000,16.500000,101532.000000,1.000000,168.000000,...,2.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000
25%,32.000000,2.003031e+07,7.000000,102703.000000,2.000000,180.000000,22.100000,102642.000000,4.000000,180.000000,...,33.000000,21.000000,10.000000,9.000000,2.000000,6.000000,20.000000,453.000000,38.000000,313.000000
50%,32.000000,2.003061e+07,19.000000,103182.000000,5.000000,185.000000,25.000000,103171.000000,7.000000,185.000000,...,43.000000,29.000000,14.000000,11.000000,4.000000,8.000000,46.000000,783.000000,73.000000,550.500000
75%,64.000000,2.003081e+07,31.000000,103758.000000,8.000000,188.000000,27.400000,103709.000000,12.000000,188.000000,...,58.000000,39.000000,19.000000,15.000000,6.000000,11.000000,87.000000,1367.500000,121.000000,945.000000
max,128.000000,2.003113e+07,295.000000,108903.000000,35.000000,208.000000,34.300000,108906.000000,35.000000,208.000000,...,179.000000,141.000000,60.000000,41.000000,21.000000,29.000000,1334.000000,4630.000000,1360.000000,4630.000000

Podemos filtar por valores no nulos para un determinado campo, de esta manera podemos hacernos una idea de que campos pueden ser interesarntes o cuales no por tener pocos datos.

In [26]:
df_filtered = df[df['winner_seed'].notna()]

In [27]:
df_filtered

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
16,2003-1536,Madrid Masters,Hard,48,M,20031013,17,103507,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4195.0,28.0,1090.0
17,2003-1536,Madrid Masters,Hard,48,M,20031013,18,102456,16.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,19.0,1240.0,146.0,258.0
19,2003-1536,Madrid Masters,Hard,48,M,20031013,20,103387,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,11.0,1845.0,23.0,1170.0
20,2003-1536,Madrid Masters,Hard,48,M,20031013,21,103819,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3825.0,127.0,290.0
23,2003-1536,Madrid Masters,Hard,48,M,20031013,24,102845,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7.0,2705.0,37.0,1000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2877,2003-891,Chennai,Hard,32,A,20021230,24,103387,2.0,NaN,...,34.0,21.0,7.0,9.0,4.0,8.0,16.0,1646.0,115.0,343.0
2879,2003-891,Chennai,Hard,32,A,20021230,26,103428,4.0,NaN,...,30.0,20.0,10.0,9.0,4.0,7.0,23.0,1240.0,155.0,239.0
2881,2003-891,Chennai,Hard,32,A,20021230,28,103387,2.0,NaN,...,48.0,32.0,9.0,10.0,4.0,8.0,16.0,1646.0,103.0,385.0
2883,2003-891,Chennai,Hard,32,A,20021230,30,103387,2.0,NaN,...,20.0,7.0,14.0,8.0,3.0,8.0,16.0,1646.0,105.0,380.0
2884,2003-891,Chennai,Hard,32,A,20021230,31,103387,2.0,NaN,...,33.0,17.0,8.0,8.0,3.0,7.0,16.0,1646.0,83.0,483.0

In [29]:
df.size

157682

Con el siguiente codigo podemos obtener el porcentaje de campos

In [32]:
total = df.size
for col in df.columns:
  df_fil = df[df[col].notna()]
  size= df_fil.size
  percent = (df_fil.size/total)*100
  print("Field " + col + " has " + str(size) + " values of " + str(total) + " (" + str(percent) + "%)")

Field tourney_id has 157682 values of 157682 (100.0%)
Field tourney_name has 157682 values of 157682 (100.0%)
Field surface has 157682 values of 157682 (100.0%)
Field draw_size has 157682 values of 157682 (100.0%)
Field tourney_level has 157682 values of 157682 (100.0%)
Field tourney_date has 157682 values of 157682 (100.0%)
Field match_num has 157682 values of 157682 (100.0%)
Field winner_id has 157682 values of 157682 (100.0%)
Field winner_seed has 60809 values of 157682 (38.564325668116844%)
Field winner_entry has 17346 values of 157682 (11.000621504039776%)
Field winner_name has 157682 values of 157682 (100.0%)
Field winner_hand has 157682 values of 157682 (100.0%)
Field winner_ht has 152341 values of 157682 (96.6128029832194%)
Field winner_ioc has 157682 values of 157682 (100.0%)
Field winner_age has 157682 values of 157682 (100.0%)
Field loser_id has 157682 values of 157682 (100.0%)
Field loser_seed has 34300 values of 157682 (21.75264139216905%)
Field loser_entry has 31164 values of 157682 (19.763828464885023%)
Field loser_name has 157682 values of 157682 (100.0%)
Field loser_hand has 157682 values of 157682 (100.0%)
Field loser_ht has 148862 values of 157682 (94.40646364201368%)
Field loser_ioc has 157682 values of 157682 (100.0%)
Field loser_age has 157682 values of 157682 (100.0%)
Field score has 157682 values of 157682 (100.0%)
Field best_of has 157682 values of 157682 (100.0%)
Field round has 157682 values of 157682 (100.0%)
Field minutes has 137494 values of 157682 (87.19701678060908%)
Field w_ace has 137641 values of 157682 (87.29024238657551%)
Field w_df has 137641 values of 157682 (87.29024238657551%)
Field w_svpt has 137641 values of 157682 (87.29024238657551%)
Field w_1stIn has 137641 values of 157682 (87.29024238657551%)
Field w_1stWon has 137641 values of 157682 (87.29024238657551%)
Field w_2ndWon has 137641 values of 157682 (87.29024238657551%)
Field w_SvGms has 137641 values of 157682 (87.29024238657551%)
Field w_bpSaved has 137641 values of 157682 (87.29024238657551%)
Field w_bpFaced has 137641 values of 157682 (87.29024238657551%)
Field l_ace has 137641 values of 157682 (87.29024238657551%)
Field l_df has 137641 values of 157682 (87.29024238657551%)
Field l_svpt has 137641 values of 157682 (87.29024238657551%)
Field l_1stIn has 137641 values of 157682 (87.29024238657551%)
Field l_1stWon has 137641 values of 157682 (87.29024238657551%)
Field l_2ndWon has 137641 values of 157682 (87.29024238657551%)
Field l_SvGms has 137641 values of 157682 (87.29024238657551%)
Field l_bpSaved has 137641 values of 157682 (87.29024238657551%)
Field l_bpFaced has 137641 values of 157682 (87.29024238657551%)
Field winner_rank has 155526 values of 157682 (98.63269111249224%)
Field winner_rank_points has 155526 values of 157682 (98.63269111249224%)
Field loser_rank has 153272 values of 157682 (97.20323182100684%)
Field loser_rank_points has 153272 values of 157682 (97.20323182100684%)

Procedemos a eliminar las columnas que tienen pocos datos puesto que no nos aportan informacion significativa (Supongo un umbral arbitrario de por debajo del 70% de registros)

In [40]:
df.columns

Index(['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level',
       'tourney_date', 'match_num', 'winner_id', 'winner_name', 'winner_hand',
       'winner_ht', 'winner_ioc', 'winner_age', 'loser_id', 'loser_name',
       'loser_hand', 'loser_ht', 'loser_ioc', 'loser_age', 'score', 'best_of',
       'round', 'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon',
       'w_2ndWon', 'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df',
       'l_svpt', 'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved',
       'l_bpFaced', 'winner_rank', 'winner_rank_points', 'loser_rank',
       'loser_rank_points'],
      dtype='object')

In [41]:
cols_to_delete = []
total = df.size
for col in df.columns:
  df_fil = df[df[col].notna()]
  size= df_fil.size
  if (df_fil.size/total) < 0.7:
    cols_to_delete.append(col)

df = df.drop(columns=cols_to_delete)
print("Se han eliminado las columnas: " + ', '.join(cols_to_delete))

Se han eliminado las columnas:

In [43]:
df.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_name,winner_hand,...,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,2003-1536,Madrid Masters,Hard,48,M,20031013,1,101965,Wayne Ferreira,R,...,NaN,NaN,NaN,NaN,NaN,NaN,28.0,1090.0,42.0,865.0
1,2003-1536,Madrid Masters,Hard,48,M,20031013,2,102358,Thomas Enqvist,R,...,NaN,NaN,NaN,NaN,NaN,NaN,146.0,258.0,40.0,950.0
2,2003-1536,Madrid Masters,Hard,48,M,20031013,3,102998,Jan Michael Gambill,R,...,NaN,NaN,NaN,NaN,NaN,NaN,57.0,660.0,43.0,855.0
3,2003-1536,Madrid Masters,Hard,48,M,20031013,4,102610,Albert Costa,R,...,NaN,NaN,NaN,NaN,NaN,NaN,23.0,1170.0,22.0,1190.0
4,2003-1536,Madrid Masters,Hard,48,M,20031013,5,102374,Alex Corretja,R,...,NaN,NaN,NaN,NaN,NaN,NaN,127.0,290.0,49.0,788.0

##Descarga en formatos alternativos de Datos Tratados##

In [44]:
df.to_excel('atp_2003_nomralized_excel.xlsx', index=False)
df.to_json('atp_2003_nomralized_json.json')

Una vez converitidos a los formatos necesarios podemos desargar los ficheros desde el gestor de archivos de Google Colab o ejecutar la siguiete celda

In [45]:
from google.colab import files
files.download('atp_2003_nomralized_excel.xlsx')
files.download('atp_2003_nomralized_json.json')